### ISSUE TITLE
[Bug]: Receive audio recordings, can't play them

### ISSUE THREAD

**Issue by mrjfilippo** [monal-im/Monal#789] opened 2022-03-12 06:37 UTC
### What Monal Release channel are you using?

AppStore

### iOS system version

15.3.1

### iOS Monal version

5.0.1 (761)

### Used XMPP server (domain)

5222.de

### How many accounts are you using in Monal?

1

### What happened?

I have a few friends on iOS using Monal. I can receive and listen to their audio recordings (I have Conversations), but they only receive my audio recordings, they can't play them. I tried with two different devices, XMPP server, and the problem was the same. All parties use OMEMO encryption.

I'll try to provide feedback as needed but I don't have an iOS device myself. 

![15839ed7-80bb-4c0f-a9ee-89a3c1f7ba73_LI - Copy](https://user-images.githubusercontent.com/60636771/158007037-55bfcecc-b909-4a7c-a17f-7d88dea4b1ff.jpg)
.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by FriedrichAltheide** [comment] 2022-03-12 06:41
Please try the beta

**Comment by mrjfilippo** [comment] 2022-03-12 06:52
Thanks for the quick reply. I'll mention it to them and reply if they get to try the beta.

**Comment by Echolon** [comment] 2022-03-12 08:29
https://testflight.apple.com/join/RjIlyvqa

**Comment by Echolon** [comment] 2022-03-12 08:35
@mrjfilippo this issue is a duplicate of two issues and a known, but already fixed bug.

#747
#362

I will close this.

**Closed as completed by Echolon** 2022-03-12 08:35 UTC
Labels: :no_entry_sign:  Bug / Stability

**Comment by Echolon** [comment] 2022-03-12 08:37
https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions#why-isnt-featureui-implemented-or-bug-fixed

**Comment by mrjfilippo** [comment] 2022-03-12 08:56
Looking forward to the next update, thanks.

Edit: Confirming the issue is fixed in the beta.
