### ISSUE TITLE
[Bug]: MUC nicknames seem to be autogenerated, cannot be changed

### ISSUE THREAD

**Issue by mirabilos** [monal-im/Monal#1319] opened 2024-12-01 21:41 UTC
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

18.1.1

### Monal version

Stable 6.4.6 (989)

### Used XMPP server (domain)

xmpp.mirbsd.org

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

0.12.3-1~bpo11+1

### How many accounts are you using in Monal?

2

### What happened?

I just set up a new server to move to, so I can decommission the old server. I created accounts for my gf and myself, and we set this up in Monal on our respective devices.

Now, the group chat has two nicknames, `mbsd` and `mbsd_`. This situation is, of course, barely tenable. I cannot find a way to change the MUC nickname, though.

### Anything else?

I disabled XEP-0352 because I’ve had trouble with reliable message transport when the corresponding module was enabled server-side.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by mirabilos** [comment] 2024-12-01 22:05
Found at least a workaround: while shat down, manually editing the bookmarks in `/var/lib/prosody/` with a text editor…

**Comment by tmolitor-stud-tu** [comment] 2024-12-01 22:19
Monal uses the part before the @ of your jid or the configured XEP-0172 display name as nick when entering mucs. if the chosen nick is already present, it appends an underscore to create an unique name.

This is a duplicate of https://github.com/monal-im/Monal/issues/1269

**Closed as completed by tmolitor-stud-tu** 2024-12-01 22:19 UTC
