### ISSUE TITLE
Monal crashes when joined to a MUC via Prosody and the mod_mam_muc module

### ISSUE THREAD

**Issue by Hund** [monal-im/Monal#718] opened 2021-07-28 12:28 UTC
### What Monal Release channel are you using?

AppStore

### iOS system version

14.6

### iOS Monal version

5.0 (750)

### Used XMPP server (domain)

My own.

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software

0.11.2

### How many accounts are you using in Monal?

1

### What happened?

When I'm connected to a MUC via Prosody which uses the mod_mam_muc module, Monal crashes. I don't have to do anything, just start Monal, wait for a few seconds and then the crash appears.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings-->Account-->(i) in server column (under advanced settings)

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment] 2021-07-28 16:12
Interesting, can you provide a log file? (Settings --> Debug --> Leftmost button on bottom button bar)
Let it crash, turn on flight mode and generate the log file.
Then upload it to https://dyn.eightysoft.de/nextcloud/index.php/s/o25SzX8zaHKomMt or send it via mail to thilo+monal@eightysoft.de

**Comment by tmolitor-stud-tu** [comment] 2021-08-03 23:56
After reading your issue and the documentation (especially the section named `Compatibility`) of `mod_mam_muc` (https://modules.prosody.im/mod_mam_muc) I advise you to use the prosody module `mod_muc_mam` included in prosody 0.11 and newer.

That should make your problem go away. I'm still interested in the logfile, though (that crash should be fixed, even if caused by a misconfiguration of the server).

**Comment by tmolitor-stud-tu** [comment] 2021-08-03 23:57
@Hund After reading your issue and the documentation (especially the section named `Compatibility`) of `mod_mam_muc` (https://modules.prosody.im/mod_mam_muc) I advise you to use the prosody module `mod_muc_mam` included in prosody 0.11 and newer.

That should make your problem go away. I'm still interested in the logfile, though (that crash should be fixed, even if caused by a misconfiguration of the server).

**Comment by Hund** [comment] 2021-08-04 12:07
> @Hund After reading your issue and the documentation (especially the section named `Compatibility`) of `mod_mam_muc` (https://modules.prosody.im/mod_mam_muc) I advise you to use the prosody module `mod_muc_mam` included in prosody 0.11 and newer.
> 
> That should make your problem go away. I'm still interested in the logfile, though (that crash should be fixed, even if caused by a misconfiguration of the server).

I'm sorry for the delay of the file. The iPhone device is not mine.

I'm also sorry if I wasn't clear enough. The issue I have with Monal is that it crashes with the module `mod_mam_muc`  **enabled**.

**Comment by Hund** [comment] 2021-08-04 12:09
Oh right. I have to solve why Monal have started to crash at every start now, before I can send you the debug log. It's not an issue related to this though.

**Comment by FriedrichAltheide** [comment] 2021-08-04 13:28
mod_mam_**muc** is not compatible with prosody 0.11. Please use mod_**muc**_mam instead. See the different placement of **muc** in the module name.


> Oh right. I have to solve why Monal have started to crash at every start now, before I can send you the debug log. It's not an issue related to this though.

Try to enable flight mode first. Or try the lastest beta (TestFlight).

**Comment by Hund** [comment] 2021-08-04 13:38
> mod_mam_**muc** is not compatible with prosody 0.11. Please use mod_**muc**_mam instead. See the different placement of **muc** in the module name.

That's.. confusing. It solved all issues enabling that. Should I close this issue now? And do you want the debug log anyway?

**Comment by FriedrichAltheide** [comment] 2021-08-04 14:15
Please upload the log to https://dyn.eightysoft.de/nextcloud/index.php/s/o25SzX8zaHKomMt or send it via mail to thilo+monal@eightysoft.de

**Comment by tmolitor-stud-tu** [comment] 2021-08-04 16:28
A debug log would still be *very* helpful :)

**Comment by tmolitor-stud-tu** [comment] 2021-08-23 14:43
@Hund it seems you won't provide a debug log, I'll close this issue then

**Closed as completed by tmolitor-stud-tu** 2021-08-23 14:43 UTC
Labels: :no_entry_sign:  Bug / Stability, :busts_in_silhouette: MUC
