### ISSUE TITLE
[Bug]Keyboard appears automatically

### ISSUE THREAD

**Issue by zpbooks** [monal-im/Monal#1050] opened 2024-05-01 15:37 UTC
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

17.4

### Monal version

6.3.0

### Used XMPP server (domain)

xmpp.jp

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

The keyboard keeps appearing automatically in the chat page. Maybe it’s a bug?
![IMG_4371](https://github.com/monal-im/Monal/assets/53597295/2163dab2-22b6-45b0-b05e-73c4f836bf98)
If not, may you add an option to choose whether to show the keyboard automatically in the chat page? Thank you

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment] 2024-05-01 19:35
Duplicate of https://github.com/monal-im/Monal/issues/704

**Comment by eLement87** [comment] 2024-05-03 07:30
~~Hi,~~

~~i think it's not a duplicate of the issue related above. Unfortunately this happends since the last update to 6.3.0 three days ago on iOS-Version 17.4.1.~~

~~If you start the chat, the keyboard directly slides in. changes its color from black to the system color and stays visible. This also happens when you change the application and go back again. You can't hide the keyboard, it bounces up and down and doesn't disappear. Even when you open a picture the interaction is note possible while the keyboard is always visible.~~

~~As @zpbooks mentioned, when you try to send a picture, the action buttons are taking up the size of the screen. And when you're at the point of sending the picture, errors appear like in issue #1052.~~

~~As an old administration trick i reinstalled the app, but same result.~~

~~Nevertheless, thank you for providing a usable xmpp messenger for ios!!~~

~~Benjamin~~


EDIT: 
Oh sorry ;) i withdraw my first sentence... after reading the other issue.
it's not a Bug it's a feature... but the other things with the bouncing and hiding are still valid

EDIT2:
I'm wasn't aware that there was already fix in the pipline. The last update this morining fixed the issues.
many thanks for your work!

**Comment by tmolitor-stud-tu** [comment] 2024-05-10 01:53
Yes, my "duplicate" meant that your bugreport reports a feature someone else wanted ;)

**Closed as completed by tmolitor-stud-tu** 2024-05-10 01:53 UTC
