### ISSUE TITLE
[Bug]: MUC, encryption not supported

### ISSUE THREAD

**Issue by pirujo** [monal-im/Monal#770] opened 2022-02-06 10:24 UTC
### What Monal Release channel are you using?

AppStore

### Used XMPP server (domain)

disroot.org

### How many accounts are you using in Monal?

1

### What happened?

A friend of mine has an iPhone with Monal installed on it. He's using with 1:1 chats without problems encrypting with OMEMO. Recently I've created a MUC in suchat.org server and invite some persons, my friend too, OMEMO encryption is working fine except for him, he gets a message about "encryption not supported". I was searching in issues section and I found this problem should be fixed in version 4.9 or 5.0.
iOS version is 14.6
Attached you can find a screen with the message.

![6456DAF1-B5E5-4EB4-9D7D-E661A2951D4E_3c1d44fe0dc6ffbfc85a024c457f444df0ac77ae](https://user-images.githubusercontent.com/45567259/152675742-e90181ef-6ea3-4dbc-8f88-c3c899969a9c.jpg)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by Echolon** [comment] 2022-02-06 10:52
Duplicate of https://github.com/monal-im/Monal/issues/769

It is not yet fully implemented.

Please be so kind and review existing issues.

**Closed as completed by Echolon** 2022-02-06 10:52 UTC
Labels: :fish: OMEMO, :busts_in_silhouette: MUC
