### ISSUE TITLE
[UX] Remove 'Save' button in preferences

### ISSUE THREAD

**Issue by haansn08** [monal-im/Monal#930] opened 2023-07-01 20:04 UTC
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

I would like to share a small user experience story for my friend who uses Monal: Recently her account got disabled for an unknown reason (she was still able to login to her account using Gajim afterwards):
<img src="https://github.com/monal-im/Monal/assets/6215916/2a1c82df-a611-4e69-bbe7-20241b4d949c" width="300"/>
After that she was unsure what to do. She tried re-enabling her account in the account settings
<img src="https://github.com/monal-im/Monal/assets/6215916/f2bc3c5c-b8d2-4d0c-8adf-c044695de996" width="300"/>
The problem was that she somehow did not notice the 'Save' button, because iOS user expectations are that app settings are applied immediately without the need to save settings. This seems like a small thing, but since users expect IM apps to "just work" even small things like that may just be the reason why somebody stops using their XMPP account. Since missing the 'Save' button in this case may render your account unusable users are more likely to give up completely on Monal here.

It also reminds me of the time a elderly relative of mine could not log into Monal, because she did not enter her credentials correctly on the first try and we checked for an hour what could have gone wrong (over the phone). I remember not finding out what went wrong. It could have been this issue, and she simply kept not saving her settings.

**Comment by lissine0** [comment] 2023-07-09 10:23
On the Privacy Settings page, on the top right, there's a `close` button that takes you back to the home page.
![ScreenShot-2023-07-09](https://github.com/monal-im/Monal/assets/138154076/039e9564-d8cf-4b58-bf32-71fb2cd20c78)
But this `close` button isn't on any other settings page.
Should we replace the `save` button on Account Settings with a `close` button? or should the `close` button be removed from Privacy Settings?

**Comment by FriedrichAltheide** [comment] 2023-07-09 12:49
The best fix would be to rewrite the UI to swiftUI **and** only allow exiting the account UI via an abort or done button (similar to the iOS mail account UI).

**Comment by lissine0** [comment] 2023-10-04 22:38
duplicate of https://github.com/monal-im/Monal/issues/745

**Comment by tmolitor-stud-tu** [comment] 2024-03-03 01:48
closing as duplicate, the privacy settings ui stuff is tracked in #993

**Comment by tmolitor-stud-tu** [comment] 2024-03-03 01:48
closing as duplicate, the privacy settings ui stuff is tracked in #993

**Closed as completed by tmolitor-stud-tu** 2024-03-03 01:48 UTC
Labels: :superhero: Help wanted, :art: UI
