### ISSUE TITLE
[Feature]: Upload media by inserting it into chat from clipboard

### ISSUE THREAD

**Issue by catap** [monal-im/Monal#1299] opened 2024-11-19 08:42 UTC
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Usually, when copy a picture or a file into clipboard you may send it via chat.

at least it expected behavior these days.

unfortunately Monal doesn’t support it, can you add it?

Thanks!

**Comment by lissine0** [comment] 2024-11-19 18:36
This is a duplicate of https://github.com/monal-im/Monal/issues/939

**Closed as completed** 2024-11-19 19:00 UTC
