### ISSUE TITLE
Two accounts being registered

### ISSUE THREAD

**Issue by jpds** [monal-im/Monal#558] opened 2021-02-06 17:54 UTC
- [x] Add unique constraint to account table.
- [x] -(NSNumber*) addAccountWithDictionary -> return if the entry already exists

### Description of my issue or feature request:

I just had two friends download 4.9.1 and after adding their accounts to Monal, they had two accounts shown in the settings and two chat windows open with me.

### The Monal version and system version I use:

4.9.1 (Build 686)

### Screenshot

![signal-2021-02-06-175925](https://user-images.githubusercontent.com/29158971/107126078-a27e2280-68a5-11eb-94f2-51ffa88129f0.jpeg)

**Comment by Echolon** [comment] 2021-02-06 18:45
Thank you very much! Can you reproduce this and provide the steps?

Wich server are you using?

**Comment by jpds** [comment] 2021-02-06 18:54
I don't use iOS myself, but I've not this issue with any other client on this server (which I'm the admin of).

It's a Prosody 0.11.7 server and my contacts already had accounts on it, they just simply installed Monal and added their accounts and had two accounts in the settings.

**Comment by FriedrichAltheide** [comment] 2021-02-07 18:24
Which iOS version?

**Comment by anurodhp** [comment] 2021-02-07 18:31
someone contacted me on the bugs email about this too. definitely something going on could be double click or something like that

**Comment by issyl0** [comment] 2021-02-08 13:01
Hey, I'm one of @jpds's friends whose Monal app has this problem. 

@FriedrichAltheide I'm running iOS 14.4.

While the two accounts are both active, I receive all messages in duplicate. I _can_ disable one of the accounts and the other one continues to work, which is what I've done for now.

If I can help by providing more info or screenshots, or by testing betas, then let me know!

**Comment by hubvu** [comment] 2021-02-08 13:31
@FriedrichAltheide As mentioned by @issyl0 I can also confirm that I am experiencing the same issue on iOS 14.4. I pulled down Monal 4.9.1, logged into the server with my account and I could view replicas 2 of the same account.

**Comment by FriedrichAltheide** [comment] 2021-02-08 15:24
We fixed some account creation bugs in the alpha. These fixes should be in the next beta. Unfortunately I could not reproduce the bug in the alpha. So we might fixed them already.

Did you use the quick setup to add your account?

**Comment by hubvu** [comment] 2021-02-08 15:54
@FriedrichAltheide great, thanks for the reply - and yes, I used the quick setup to add the account. Let me know if you need anything else.

Looking forward to the new release - hopefully the replica issue will be resolved.

**Comment by FriedrichAltheide** [comment] 2021-02-08 16:44
- [ ] Add unique constraint to account table.
- [ ] -(NSNumber*) addAccountWithDictionary -> return if the entry already exists

**Comment by Echolon** [comment] 2021-02-08 20:50
>     * [ ]  Add unique constraint to account table.
> 
>     * [ ]  -(NSNumber*) addAccountWithDictionary -> return if the entry already exists

I added the task to the very first comment to get it recognized by Github

**Comment by Echolon** [comment] 2021-02-24 20:28
The merging has not closed this. I will do so.

**Closed by Echolon** 2021-02-24 20:28 UTC
Labels: :iphone: iOS, :no_entry_sign:  Bug / Stability

**Comment by FriedrichAltheide** [comment] 2021-02-27 05:51
the first 5.0 beta was released yesterday on TestFlight. Reopen if you can still create two accounts for the same jid
