### ISSUE TITLE
Cannot add/invite users to MUC

### ISSUE THREAD

**Issue by NagarajuMetavoxx** [monal-im/Monal#158] opened 2019-01-04 09:45 UTC
In my iOS application, I can able to create the groups (in Groups Tab). But I didn't find option to add/invite an user to that particular group

<img src="https://user-images.githubusercontent.com/46367348/50682138-e69df980-1033-11e9-816f-6058dd300330.PNG" width="300">

**Comment by Echolon** [comment] 2019-01-05 14:36
Yep, I think this is a very important function. I would also add something like:

once you created a group, the software directely askes you to invite people. Or as there is no one in the group, a button shows up in the chat windows which suggest to invite people

**Comment by Echolon** [comment] 2020-01-04 22:55
@NagarajuMetavoxx 

Is that still not possible in MUCs in the latest release?

**Comment by Echolon** [comment] 2020-07-14 18:20
ref. **XEP-0048: Bookmarks** #19

**Comment by tmolitor-stud-tu** [comment] 2021-05-21 18:13
duplicate of #41

**Closed by tmolitor-stud-tu** 2021-05-21 18:13 UTC
Labels: :busts_in_silhouette: MUC, :tada: Feature
