### ISSUE TITLE
[Feature]: Please Implement XEP - 0444 (Message Reactions)

### ISSUE THREAD

**Issue by gachikuku** [monal-im/Monal#978] opened 2023-11-20 01:11 UTC
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

It makes for more expressive and swift communication 🤗

**Comment by FriedrichAltheide** [comment] 2023-11-20 03:21
Duplicate of #554

**Closed as not planned by FriedrichAltheide** 2023-11-20 03:21 UTC
