### ISSUE TITLE
[macOS] Display posted URLs, make URLs copyable 

### ISSUE THREAD

**Issue by eun-ice** [monal-im/Monal#235] opened 2019-04-23 08:39 UTC
Monal If someone posts a link to a password protected site or a link that is not reachable for the Monal client, it sometimes gets displayed as "something.com" 
![Screenshot 2019-04-23 at 10 35 01](https://user-images.githubusercontent.com/17766811/56566663-7d76cd80-65b3-11e9-886f-95ebdad70677.png)

There is no way to actually see what link the user posted besides clicking on them.

This is especially annoying if someone posts multiple links and you want to come back and open a specific link, with multiple "something.com" bubbles, you cannot figure out which one you want.

Also sometimes you do not want to open a link in the browser but copy it to clipboard.

My suggestions:

- Always display the URL of a posted link (maybe shortened and full URL on hover)
- Just display the link as inline text link if you cannot fetch meta data (never show something.com)
- Make URLs right-clickable with "open" and "copy to clipboard"

**Comment by Echolon** [comment] 2021-01-26 18:20
@foss- is that still a thing on Mac?

**Comment by foss-** [comment] 2021-01-26 18:35
Do we have an actual URL to reproduce at hand?

**Comment by Echolon** [comment] 2021-03-08 08:25
@eun-ice Hi, may you provide steps to reproduce?

**Comment by foss-** [comment] 2021-03-08 10:40
This issue touches on several aspects:

- wrong placeholder string `something.com`(FIXED)
- no way to see full link (persisting)

I have not seen a something.com link in a long time so think it is fair to assume this has been addressed. The question now is, do we agree not showing the full link is still a problem while at the same time link preview is now supported and working?

The original problem of being unable to differentiate multiple links is no longer valid with working link preview:
<img width="210" alt="link preview" src="https://user-images.githubusercontent.com/5708172/110310572-fdb94700-8002-11eb-9da3-beb557bf42a2.png">

**Comment by Echolon** [comment] 2021-03-08 11:18
Hmn, lets wait what the devs say. Mayve we need to put it into a new stated issue

**Comment by STPKITT** [comment] 2021-03-08 12:21
At least there needs to be a way for the user to see the full URL without opening it in the webbrowser. Maybe "show full URL" could be made available via a long click or something like that.

**Comment by Echolon** [comment] 2021-03-08 19:41
Hey @FriedrichAltheide
If the Catalyst label was removed for the reason Catalyst is out dated, we should rather rename the label.
If the issue is not a MacOS issue anymore then is fine to remove

**Comment by tmolitor-stud-tu** [comment] 2024-06-10 09:16
Is this still the case? Does swiping the link preview bubble to the left and select copy to copy the url help?

I'm closing this for now, feel free to request a reopen, if this isn't solved yet :)

**Closed by tmolitor-stud-tu** 2024-06-10 09:16 UTC
Labels: :tada: Feature, Chat-UI Rewrite

**Comment by foss-** [comment] 2024-06-10 11:00
Sliding the message and clicking copy works to copy link URL (if you have a trackpad that is).
